// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bjzqfmmowlghbmsyigwm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJqenFmbW1vd2xnaGJtc3lpZ3dtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxMjAwMzgsImV4cCI6MjA2MjY5NjAzOH0.4cf7hnJ5yGIU8LR58YV2w1g8ESz0ywRppYF2lagOxOA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);